theme: jekyll-theme-cayman
title: welcome to Geoff1900's HomePage

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "10.8.0"

